# -*- coding: utf-8 -*-
"""Gérer les données nuPlan sur GitHub

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1JE2ZVcbnXCKbUha0I_c0HABULSj9gW

C'est compris. Reprenons sur des bases plus solides, structurées et directement applicables pour ton projet.

Ton sujet, la **prédiction de désengagement** (quand le véhicule doit rendre la main à l'humain), est passionnant et touche directement à ce qu'on appelle l'ODD (*Operational Design Domain*) dans tes cours Coursera.

Cependant, il faut aborder un problème technique immédiat : la gestion des données face aux limites matérielles de ton coéquipier.

### 1. La réalité sur GitHub et les gros fichiers

Je dois être direct : **tu ne peux pas mettre les datasets nuPlan sur GitHub.**

* **Les limites de Git :** GitHub bloque les fichiers de plus de 100 Mo. Même avec Git LFS (Large File Storage), stocker des dizaines de gigaoctets (comme les 37 Go de Singapour) va bloquer votre dépôt et coûter très cher.
* **Le rôle de Git :** Git est conçu pour versionner du *code source* (des fichiers texte légers), pas des bases de données brutes.

**Le bon workflow de collaboration :**

1. Le code va sur **GitHub**.
2. Les données vont sur un cloud de stockage (Google Drive, OneDrive, ou un disque dur externe) que ton coéquipier télécharge localement sur son PC.
3. Vous utilisez un fichier `.gitignore` pour empêcher le code d'envoyer les données sur GitHub par erreur.

---

### 2. Comment coder pour un PC avec 8-16 Go de RAM ?

Ton coéquipier ne pourra jamais charger un fichier de 37 Go dans sa RAM. La solution s'appelle le **Lazy Loading** (ou lecture par morceaux). Puisque nuPlan utilise des bases de données SQLite (`.db`), on peut lire les données ligne par ligne sans saturer la mémoire.

Voici le code exact (à mettre sur votre GitHub) que ton coéquipier devra utiliser pour charger les données de manière sécurisée pour sa RAM :
"""

import sqlite3
import pandas as pd
import os

def load_nuplan_in_chunks(db_path, table_name, chunk_size=5000):
    """
    Générateur pour lire une table nuPlan par blocs.
    Idéal pour les PC avec 8-16 Go de RAM.
    """
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"Le fichier {db_path} est introuvable. L'as-tu bien téléchargé localement ?")

    # Connexion à la base SQLite
    conn = sqlite3.connect(db_path)

    # Requête pour récupérer les données (ex: lidar, ego_pose, etc.)
    query = f"SELECT * FROM {table_name}"

    print(f"Début de la lecture de la table '{table_name}' par blocs de {chunk_size}...")

    # pd.read_sql avec chunksize renvoie un itérateur
    try:
        for chunk in pd.read_sql_query(query, conn, chunksize=chunk_size):
            yield chunk # Le mot-clé 'yield' permet de traiter un bloc avant de charger le suivant
    finally:
        conn.close()

# --- Exemple d'utilisation pour ton coéquipier ---
if __name__ == "__main__":
    # Il doit pointer vers le chemin où IL a mis les données sur SON pc
    # Conseil : Commencez UNIQUEMENT par le "nuPlan Mini Split" (8.25 GB)
    LOCAL_DB_PATH = "data/nuplan_mini/nuplan_mini.db"

    # Exemple: on itère sur les morceaux sans faire exploser la RAM
    # for df_chunk in load_nuplan_in_chunks(LOCAL_DB_PATH, 'ego_pose'):
    #     print(f"Bloc chargé avec succès. Taille de ce bloc en RAM: {df_chunk.memory_usage(deep=True).sum() / 1e6:.2f} MB")
    #     # Mettre ici le code d'entraînement ou de traitement ML

"""---

### 3. Ton modèle de `README.md` et `.gitignore`

Pour que votre projet GitHub soit propre dès le premier jour, voici ce que tu dois initialiser.

**Fichier `.gitignore` (à la racine du projet) :**

```text
# Ignorer les bases de données et dossiers de données
*.db
*.zip
data/
datasets/

# Ignorer les environnements virtuels Python
venv/
env/
.env

# Ignorer les fichiers temporaires
__pycache__/
*.pyc

```

**Fichier `README.md` (pour guider ton coéquipier et le prof) :**

```markdown
# 🚗 Prédiction de Désengagement (Autonomous Driving ML)

Ce projet vise à prédire l'incapacité d'une IA de conduite autonome face à son environnement (sortie de l'ODD - Operational Design Domain), nécessitant de rendre la main à un conducteur humain.

## 📊 Dataset utilisé : nuPlan (Motional)
Nous utilisons le dataset nuPlan. **Attention : Ne commitez jamais les fichiers `.db` sur GitHub !**

### Installation et Configuration

1. **Cloner le dépôt :**
   ```bash
   git clone [https://github.com/votre-nom/votre-projet.git](https://github.com/votre-nom/votre-projet.git)
   cd votre-projet

```

2. **Télécharger les données :**
* Créez un dossier `data/` à la racine du projet (il sera ignoré par Git).
* Téléchargez le **nuPlan Mini Split (8.25 GB)** depuis le site officiel.
* Placez les fichiers `.db` extraits dans le dossier `data/`.


3. **Installer les dépendances :**
```bash
pip install pandas sqlite3 scikit-learn
# Optionnel mais recommandé : pip install nuplan-devkit

```



## 🧠 Architecture du Code

* `src/data_loader.py` : Script de chargement optimisé pour les PC avec RAM limitée (Lazy Loading).
* `src/features.py` : Extraction des conditions environnementales (pluie, densité du trafic).
* `src/model.py` : Modèle de prédiction de désengagement.

```

---

### Le lien avec Coursera (Pour aller plus loin)
Dans tes cours, tu as sûrement entendu parler de *Sensor Fusion* (Fusion de capteurs) ou de *State Estimation*. Pour prédire que l'IA va échouer, ton modèle ML devra repérer des **anomalies** dans ces étapes. Par exemple : si la variance des données LiDAR augmente d'un coup (à cause de la pluie bloquant le laser), c'est un signal fort pour déclencher le rendu de contrôle à l'humain.

Souhaites-tu que je t'explique comment utiliser la librairie officielle `nuplan-devkit` (créée par Motional) pour extraire spécifiquement la météo et la densité du trafic de ces fichiers `.db` ?

```
"""